### ISSUE TITLE
FpBankConnections.query handles json incorrectly

### ISSUE THREAD

**Issue by ChristianSch** [proshin-roman/finapi-java-client#115]
When querying for a users bank connections, the lib tries to interpret the json incorrectly.

Example:

```
FpBankConnections bc = new FpBankConnections(someEndpoint, someToken);
return bc.query(bankIds);
```
results in:
```
A JSONArray text must start with '[' at 1 [character 2 line 1]
org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.JSONArray.<init>(JSONArray.java:109)
	at org.json.JSONArray.<init>(JSONArray.java:162)
	at org.proshin.finapi.bankconnection.FpBankConnections.query(FpBankConnections.java:61)
```

I'll see that I can PR my fix soon.

**Comment by proshin-roman** [comment]
@ChristianSch sorry for so long answer - I wasn't notified about this new bug. I will check my GitHub notifications settings so that it doesn't happen again in the future.

**Comment by proshin-roman** [comment]
@ChristianSch your pull request has been merged and the fix will be published in the next release. Although it's already available in the latest SNAPSHOT version. Please, check if the issue can be closed now.

**Comment by proshin-roman** [comment]
@ChristianSch I will close the issue as it is already fixed and I want to release a new version that will include the fix.
