### ISSUE TITLE
Update library up to v1.64.0

### ISSUE THREAD

**Issue by proshin-roman** [proshin-roman/finapi-java-client#130]

**Comment by 0pdd** [comment]
@proshin-roman 2 puzzles [#138](https://github.com/proshin-roman/finapi-java-client/issues/138), [#139](https://github.com/proshin-roman/finapi-java-client/issues/139) are still not solved.

**Comment by 0pdd** [comment]
@proshin-roman the puzzle [#139](https://github.com/proshin-roman/finapi-java-client/issues/139) is still not solved; solved: [#138](https://github.com/proshin-roman/finapi-java-client/issues/138).

**Comment by 0pdd** [comment]
@proshin-roman the puzzle [#143](https://github.com/proshin-roman/finapi-java-client/issues/143) is still not solved; solved: [#138](https://github.com/proshin-roman/finapi-java-client/issues/138), [#139](https://github.com/proshin-roman/finapi-java-client/issues/139).

**Comment by 0pdd** [comment]
@proshin-roman all 3 puzzles are solved here: [#138](https://github.com/proshin-roman/finapi-java-client/issues/138), [#139](https://github.com/proshin-roman/finapi-java-client/issues/139), [#143](https://github.com/proshin-roman/finapi-java-client/issues/143).
