### ISSUE TITLE
Migrate existing tests which use this FakeEndpoint class to...

### ISSUE THREAD

**Issue by 0pdd** [proshin-roman/finapi-java-client#143]
The puzzle `139-69030b2f` from #139 has to be resolved: 

https://github.com/proshin-roman/finapi-java-client/blob/79e3eb343907f2a84e1d259bee66b7dccee3434f/src/test/java/org/proshin/finapi/fake/FakeEndpoint.java#L30-L31

The puzzle was created by Roman Proshin on 16-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by proshin-roman** [comment]
More info about the mocking server here: http://www.mock-server.com/mock_server/getting_started.html

**Comment by 0pdd** [comment]
The puzzle `139-69030b2f` has disappeared from the source code, that's why I closed this issue.
