### ISSUE TITLE
Stabilize code of Bank connections services: finish implementation and write tests

### ISSUE THREAD

**Issue by proshin-roman** [proshin-roman/finapi-java-client#20]

**Comment by 0pdd** [comment]
@proshin-roman 2 puzzles [#46](https://github.com/proshin-roman/finapi-java-client/issues/46), [#47](https://github.com/proshin-roman/finapi-java-client/issues/47) are still not solved.

**Comment by 0pdd** [comment]
@proshin-roman 3 puzzles [#122](https://github.com/proshin-roman/finapi-java-client/issues/122), [#123](https://github.com/proshin-roman/finapi-java-client/issues/123), [#47](https://github.com/proshin-roman/finapi-java-client/issues/47) are still not solved; solved: [#46](https://github.com/proshin-roman/finapi-java-client/issues/46).

**Comment by 0pdd** [comment]
@proshin-roman 2 puzzles [#123](https://github.com/proshin-roman/finapi-java-client/issues/123), [#47](https://github.com/proshin-roman/finapi-java-client/issues/47) are still not solved; solved: [#122](https://github.com/proshin-roman/finapi-java-client/issues/122), [#46](https://github.com/proshin-roman/finapi-java-client/issues/46).

**Comment by 0pdd** [comment]
@proshin-roman all 4 puzzles are solved here: [#122](https://github.com/proshin-roman/finapi-java-client/issues/122), [#123](https://github.com/proshin-roman/finapi-java-client/issues/123), [#46](https://github.com/proshin-roman/finapi-java-client/issues/46), [#47](https://github.com/proshin-roman/finapi-java-client/issues/47).
