### ISSUE TITLE
Stabilize code of Accounts services: finish implementation and write tests

### ISSUE THREAD

**Issue by proshin-roman** [proshin-roman/finapi-java-client#21]

**Comment by 0pdd** [comment]
@proshin-roman 3 puzzles [#69](https://github.com/proshin-roman/finapi-java-client/issues/69), [#70](https://github.com/proshin-roman/finapi-java-client/issues/70), [#71](https://github.com/proshin-roman/finapi-java-client/issues/71) are still not solved; solved: [#unknown](), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@proshin-roman 5 puzzles [#108](https://github.com/proshin-roman/finapi-java-client/issues/108), [#109](https://github.com/proshin-roman/finapi-java-client/issues/109), [#69](https://github.com/proshin-roman/finapi-java-client/issues/69), [#70](https://github.com/proshin-roman/finapi-java-client/issues/70), [#71](https://github.com/proshin-roman/finapi-java-client/issues/71) are still not solved; solved: [#unknown](), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@proshin-roman 4 puzzles [#108](https://github.com/proshin-roman/finapi-java-client/issues/108), [#109](https://github.com/proshin-roman/finapi-java-client/issues/109), [#70](https://github.com/proshin-roman/finapi-java-client/issues/70), [#71](https://github.com/proshin-roman/finapi-java-client/issues/71) are still not solved; solved: [#69](https://github.com/proshin-roman/finapi-java-client/issues/69), [#unknown](), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@proshin-roman 3 puzzles [#108](https://github.com/proshin-roman/finapi-java-client/issues/108), [#109](https://github.com/proshin-roman/finapi-java-client/issues/109), [#70](https://github.com/proshin-roman/finapi-java-client/issues/70) are still not solved; solved: [#69](https://github.com/proshin-roman/finapi-java-client/issues/69), [#71](https://github.com/proshin-roman/finapi-java-client/issues/71), [#unknown](), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@proshin-roman 2 puzzles [#108](https://github.com/proshin-roman/finapi-java-client/issues/108), [#70](https://github.com/proshin-roman/finapi-java-client/issues/70) are still not solved; solved: [#109](https://github.com/proshin-roman/finapi-java-client/issues/109), [#69](https://github.com/proshin-roman/finapi-java-client/issues/69), [#71](https://github.com/proshin-roman/finapi-java-client/issues/71), [#unknown](), [#unknown](), [#unknown]().
