### ISSUE TITLE
Adjust the library for PSD2 changes

### ISSUE THREAD

**Issue by proshin-roman** [proshin-roman/finapi-java-client#240]

**Comment by 0pdd** [comment]
@proshin-roman 8 puzzles [#261](https://github.com/proshin-roman/finapi-java-client/issues/261), [#262](https://github.com/proshin-roman/finapi-java-client/issues/262), [#263](https://github.com/proshin-roman/finapi-java-client/issues/263), [#264](https://github.com/proshin-roman/finapi-java-client/issues/264), [#265](https://github.com/proshin-roman/finapi-java-client/issues/265), [#266](https://github.com/proshin-roman/finapi-java-client/issues/266), [#267](https://github.com/proshin-roman/finapi-java-client/issues/267), [#268](https://github.com/proshin-roman/finapi-java-client/issues/268) are still not solved.

**Comment by 0pdd** [comment]
@proshin-roman 7 puzzles [#261](https://github.com/proshin-roman/finapi-java-client/issues/261), [#262](https://github.com/proshin-roman/finapi-java-client/issues/262), [#263](https://github.com/proshin-roman/finapi-java-client/issues/263), [#264](https://github.com/proshin-roman/finapi-java-client/issues/264), [#265](https://github.com/proshin-roman/finapi-java-client/issues/265), [#266](https://github.com/proshin-roman/finapi-java-client/issues/266), [#267](https://github.com/proshin-roman/finapi-java-client/issues/267) are still not solved; solved: [#268](https://github.com/proshin-roman/finapi-java-client/issues/268).

**Comment by 0pdd** [comment]
@proshin-roman 6 puzzles [#261](https://github.com/proshin-roman/finapi-java-client/issues/261), [#262](https://github.com/proshin-roman/finapi-java-client/issues/262), [#263](https://github.com/proshin-roman/finapi-java-client/issues/263), [#264](https://github.com/proshin-roman/finapi-java-client/issues/264), [#265](https://github.com/proshin-roman/finapi-java-client/issues/265), [#266](https://github.com/proshin-roman/finapi-java-client/issues/266) are still not solved; solved: [#267](https://github.com/proshin-roman/finapi-java-client/issues/267), [#268](https://github.com/proshin-roman/finapi-java-client/issues/268).

**Comment by 0pdd** [comment]
@proshin-roman 5 puzzles [#261](https://github.com/proshin-roman/finapi-java-client/issues/261), [#262](https://github.com/proshin-roman/finapi-java-client/issues/262), [#263](https://github.com/proshin-roman/finapi-java-client/issues/263), [#264](https://github.com/proshin-roman/finapi-java-client/issues/264), [#265](https://github.com/proshin-roman/finapi-java-client/issues/265) are still not solved; solved: [#266](https://github.com/proshin-roman/finapi-java-client/issues/266), [#267](https://github.com/proshin-roman/finapi-java-client/issues/267), [#268](https://github.com/proshin-roman/finapi-java-client/issues/268).

**Comment by 0pdd** [comment]
@proshin-roman 4 puzzles [#261](https://github.com/proshin-roman/finapi-java-client/issues/261), [#262](https://github.com/proshin-roman/finapi-java-client/issues/262), [#263](https://github.com/proshin-roman/finapi-java-client/issues/263), [#264](https://github.com/proshin-roman/finapi-java-client/issues/264) are still not solved; solved: [#265](https://github.com/proshin-roman/finapi-java-client/issues/265), [#266](https://github.com/proshin-roman/finapi-java-client/issues/266), [#267](https://github.com/proshin-roman/finapi-java-client/issues/267), [#268](https://github.com/proshin-roman/finapi-java-client/issues/268).

**Comment by 0pdd** [comment]
@proshin-roman 3 puzzles [#261](https://github.com/proshin-roman/finapi-java-client/issues/261), [#262](https://github.com/proshin-roman/finapi-java-client/issues/262), [#263](https://github.com/proshin-roman/finapi-java-client/issues/263) are still not solved; solved: [#264](https://github.com/proshin-roman/finapi-java-client/issues/264), [#265](https://github.com/proshin-roman/finapi-java-client/issues/265), [#266](https://github.com/proshin-roman/finapi-java-client/issues/266), [#267](https://github.com/proshin-roman/finapi-java-client/issues/267), [#268](https://github.com/proshin-roman/finapi-java-client/issues/268).

**Comment by 0pdd** [comment]
@proshin-roman all 8 puzzles are solved here: [#261](https://github.com/proshin-roman/finapi-java-client/issues/261), [#262](https://github.com/proshin-roman/finapi-java-client/issues/262), [#263](https://github.com/proshin-roman/finapi-java-client/issues/263), [#264](https://github.com/proshin-roman/finapi-java-client/issues/264), [#265](https://github.com/proshin-roman/finapi-java-client/issues/265), [#266](https://github.com/proshin-roman/finapi-java-client/issues/266), [#267](https://github.com/proshin-roman/finapi-java-client/issues/267), [#268](https://github.com/proshin-roman/finapi-java-client/issues/268).
