### ISSUE TITLE
importing a new bank connection with an outdated token fails with a JSON exception

### ISSUE THREAD

**Issue by ChristianSch** [proshin-roman/finapi-java-client#241]
Hi there,

So when trying to import a new bank connection with an outdated token I get the following exception:

```
org.json.JSONException: JSONObject["errors"] not found.
	at org.json.JSONObject.get(JSONObject.java:566) ~[json-20180813.jar:na]
	at org.json.JSONObject.getJSONArray(JSONObject.java:760) ~[json-20180813.jar:na]
	at org.proshin.finapi.exception.FinapiException.errors(FinapiException.java:62) ~[finapi-java-client-0.1.73.jar:0.1.73]
```

Now the problem is, the response of course only has the field `error`, as specified in the documentation (https://sandbox.finapi.io/#!/General_Information/errorResponses). 

You can reproduce it with something like the following. 
```
FpBankConnections conn = new FpBankConnections(getEndpoint(), userToken);
Future<BankConnection> bankConnectionFuture = conn.importNew(new ImportParameters().withBank(bankId));

// invalidate the token
FpAccessTokens tokens = new FpAccessTokens(getEndpoint());
tokens.revoke(getClientToken(), accessToken, AccessTokens.RevokeToken.ACCESS_TOKEN_ONLY);

try {
    bankConnectionFuture.get();
} catch (ExecutionException e) {
    Exception cause = (FinapiException) e.getCause();
    for (FinapiError error : cause.errors()) {
    }
}
```

The problem lies in:
https://github.com/proshin-roman/finapi-java-client/blob/e24d01726503cdb5f55fdfc2550f76af3d7b9c70/src/main/java/org/proshin/finapi/exception/FinapiException.java#L60-L65

Now I would've tried to fix this on my own and provide a PR, but this is something that might need a decision on your end. `errors` is clearly dependent on the context and might need some work on the exceptions (a special one for outdated tokens?). Let me know what you think, maybe I can help.

**Comment by ccostin93** [comment]
I think the cleaner solution would be to create a new exception: `FinapiAuthenticationFailedError` which will be thrown when HTTP code 403 Forbidden is received

https://github.com/proshin-roman/finapi-java-client/blob/e24d01726503cdb5f55fdfc2550f76af3d7b9c70/src/main/java/org/proshin/finapi/endpoint/FpEndpoint.java#L69-L72

Authentication invalid/expired is a special case that returns a different error format compared with the other finAPI errors.

@proshin-roman what do you think?

**Comment by proshin-roman** [comment]
@ccostin93 yeah, I think it's a good idea. It definitely should be a new class as the response signature is different.
