### ISSUE TITLE
client/user token implementations leak credentials in logs

### ISSUE THREAD

**Issue by ChristianSch** [proshin-roman/finapi-java-client#243]
Hi,

As both client and user token implementations use query strings, the credentials can actually leak in any logs on the server (mine/our/the clients). It is preferred to actually include them in the request body instead. Quoting the [api doc](https://sandbox.finapi.io/#!/Authorization/getToken):

```
• Even though finAPI is not logging query parameters, it is still recommended to pass the parameters in the POST body instead of in the URL. Also, please set the Content-Type of your request to 'application/x-www-form-urlencoded' when calling this service.
```

Relevant: https://github.com/proshin-roman/finapi-java-client/issues/37

**Comment by proshin-roman** [comment]
Hi Christian,
thanks for the request! 
Yes, you're right about this issue - all credentials should be submitted in the body of a request. This is a bug and it will be fixed (feel free to submit a pull request).

**Comment by ccostin93** [comment]
@proshin-roman Will try to fix this issue over the weekend
