### ISSUE TITLE
Configure releasing process via rultor.com

### ISSUE THREAD

**Issue by proshin-roman** [proshin-roman/finapi-java-client#256]
Here is the "how to" link: https://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html

**Comment by proshin-roman** [comment]
@rultor release, tag is `0.1.78`

**Comment by proshin-roman** [comment]
It seems rultor doesn't download assets from the linked private repo - I've submitted a bug to the rultor project https://github.com/yegor256/rultor/issues/1323

**Comment by ccostin93** [comment]
@proshin-roman The issue was fixed.

> @proshin-roman use the latest yegor256/rultor-image and the problem will disappear

**Comment by proshin-roman** [comment]
@rultor  release, tag is `0.1.92`

**Comment by proshin-roman** [comment]
@rultor release, tag is `0.1.92`

**Comment by proshin-roman** [comment]
@rultor release, tag is `0.1.92`

**Comment by proshin-roman** [comment]
@rultor release, tag is `0.1.92`

**Comment by ccostin93** [comment]
@rultor release, tag is 0.1.92

**Comment by proshin-roman** [comment]
@rultor release, tag `0.1.92`

**Comment by proshin-roman** [comment]
@rultor release, tag is `0.1.92`
