### ISSUE TITLE
Bank search not working when using two words split by space

### ISSUE THREAD

**Issue by bzagozda** [proshin-roman/finapi-java-client#279]
Hi,

when using for example `new FpBanks(..).search(new BanksCriteria().withSearch("Sparkasse Heid"))`
I don't get any results, even though when using finapi `https://sandbox.finapi.io/api/v1/banks` directly for given search string i get 4 results.
The thing is that url builder replaces whitespace with %2B instead %20 which doesn't work with finapi.

**Comment by proshin-roman** [comment]
The bug should be fixed as it's explained here: https://github.com/proshin-roman/finapi-java-client/pull/280#issuecomment-723051425

**Comment by ptrepka** [comment]
When do you plan to push those changes to maven repo?
