### ISSUE TITLE
inspecode.rocro.com badge is not working

### ISSUE THREAD

**Issue by proshin-roman** [proshin-roman/finapi-java-client#283]
This badge is not working.
Create ticket to delete or fix?

_Originally posted by @ccostin93 in https://github.com/proshin-roman/finapi-java-client/pull/281/files_

First, try to fix the badge. Otherwise, delete it and also delete any integrations with the service.

**Comment by ccostin93** [comment]
@proshin-roman I am not sure what integration you have with inspecode rocro.

I couldn't find anything in the project related to this integration. Nor is there any feedback in any PRs that inspecode.rocro is doing anything, so I will just remove this badge.
