### ISSUE TITLE
Service "Authorization - Revoke a token" is not supported

### ISSUE THREAD

**Issue by proshin-roman** [proshin-roman/finapi-java-client#32]

**Comment by 0pdd** [comment]
@proshin-roman the puzzle [#34](https://github.com/proshin-roman/finapi-java-client/issues/34) is still not solved.

**Comment by 0pdd** [comment]
@proshin-roman the only puzzle [#34](https://github.com/proshin-roman/finapi-java-client/issues/34) is solved here.
