### ISSUE TITLE
Configure 0pdd for the project

### ISSUE THREAD

**Issue by proshin-roman** [proshin-roman/finapi-java-client#8]

**Comment by 0pdd** [comment]
@proshin-roman 2 puzzles [#13](https://github.com/proshin-roman/finapi-java-client/issues/13), [#14](https://github.com/proshin-roman/finapi-java-client/issues/14) are still not solved.

**Comment by 0pdd** [comment]
@proshin-roman 4 puzzles [#13](https://github.com/proshin-roman/finapi-java-client/issues/13), [#14](https://github.com/proshin-roman/finapi-java-client/issues/14), [#37](https://github.com/proshin-roman/finapi-java-client/issues/37), [#38](https://github.com/proshin-roman/finapi-java-client/issues/38) are still not solved.

**Comment by 0pdd** [comment]
@proshin-roman 5 puzzles [#13](https://github.com/proshin-roman/finapi-java-client/issues/13), [#14](https://github.com/proshin-roman/finapi-java-client/issues/14), [#37](https://github.com/proshin-roman/finapi-java-client/issues/37), [#42](https://github.com/proshin-roman/finapi-java-client/issues/42), [#43](https://github.com/proshin-roman/finapi-java-client/issues/43) are still not solved; solved: [#38](https://github.com/proshin-roman/finapi-java-client/issues/38).

**Comment by 0pdd** [comment]
@proshin-roman 3 puzzles [#37](https://github.com/proshin-roman/finapi-java-client/issues/37), [#42](https://github.com/proshin-roman/finapi-java-client/issues/42), [#74](https://github.com/proshin-roman/finapi-java-client/issues/74) are still not solved; solved: [#13](https://github.com/proshin-roman/finapi-java-client/issues/13), [#14](https://github.com/proshin-roman/finapi-java-client/issues/14), [#38](https://github.com/proshin-roman/finapi-java-client/issues/38), [#43](https://github.com/proshin-roman/finapi-java-client/issues/43).

**Comment by 0pdd** [comment]
@proshin-roman 2 puzzles [#37](https://github.com/proshin-roman/finapi-java-client/issues/37), [#74](https://github.com/proshin-roman/finapi-java-client/issues/74) are still not solved; solved: [#13](https://github.com/proshin-roman/finapi-java-client/issues/13), [#14](https://github.com/proshin-roman/finapi-java-client/issues/14), [#38](https://github.com/proshin-roman/finapi-java-client/issues/38), [#42](https://github.com/proshin-roman/finapi-java-client/issues/42), [#43](https://github.com/proshin-roman/finapi-java-client/issues/43).

**Comment by 0pdd** [comment]
@proshin-roman the puzzle [#37](https://github.com/proshin-roman/finapi-java-client/issues/37) is still not solved; solved: [#13](https://github.com/proshin-roman/finapi-java-client/issues/13), [#14](https://github.com/proshin-roman/finapi-java-client/issues/14), [#38](https://github.com/proshin-roman/finapi-java-client/issues/38), [#42](https://github.com/proshin-roman/finapi-java-client/issues/42), [#43](https://github.com/proshin-roman/finapi-java-client/issues/43), [#74](https://github.com/proshin-roman/finapi-java-client/issues/74).
